spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gateway
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
#  typeAliasesPackage: com.xdd.entity
  mapperLocations: classpath:cn/springframework/cloud/gateway/mapper/*.xml
